# Generated by Django 4.0.5 on 2022-06-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_reply_post_reply_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.PositiveIntegerField(null=True, verbose_name='댓글수')),
            ],
        ),
    ]
