# Generated by Django 4.0.5 on 2022-06-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0003_free'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Free',
        ),
    ]
